name: Build extension

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Clear hotreload
        run: |
          echo "" > src/data/hotreload.js

      - name: Move to manifest v2
        run: |
          rm -f src/manifest.json
          cp src/manifest_v2.json src/manifest.json

      - name: "web-ext build"
        id: web-ext-build
        uses: kewisch/action-web-ext@v1
        with:
          cmd: build
          source: src
          filename: "ISSDCAC.xpi"

      - uses: actions/upload-artifact@v4
        with:
          name: ISSDCAC-firefox-source
          path: ./src/*

      - uses: actions/upload-artifact@v4
        with:
          name: ISSDCAC-firefox-unsigned
          path: ${{ steps.web-ext-build.outputs.target }}
